// @flow

export const PLUGINS = [
  "check-es2015-constants",
  "external-helpers-2",
  "syntax-async-functions",
  "syntax-async-generators",
  "syntax-class-constructor-call",
  "syntax-class-properties",
  "syntax-decorators",
  "syntax-do-expressions",
  "syntax-exponentiation-operator",
  "syntax-export-extensions",
  "syntax-flow",
  "syntax-function-bind",
  "syntax-function-sent",
  "syntax-jsx",
  "syntax-object-rest-spread",
  "syntax-trailing-function-commas",
  "transform-async-functions",
  "transform-async-to-generator",
  "transform-async-to-module-method",
  "transform-class-constructor-call",
  "transform-class-properties",
  "transform-decorators",
  "transform-decorators-legacy",
  "transform-do-expressions",
  "transform-es2015-arrow-functions",
  "transform-es2015-block-scoped-functions",
  "transform-es2015-block-scoping",
  "transform-es2015-classes",
  "transform-es2015-computed-properties",
  "transform-es2015-destructuring",
  "transform-es2015-duplicate-keys",
  "transform-es2015-for-of",
  "transform-es2015-function-name",
  "transform-es2015-instanceof",
  "transform-es2015-literals",
  "transform-es2015-modules-amd",
  "transform-es2015-modules-commonjs",
  "transform-es2015-modules-systemjs",
  "transform-es2015-modules-umd",
  "transform-es2015-object-super",
  "transform-es2015-parameters",
  "transform-es2015-shorthand-properties",
  "transform-es2015-spread",
  "transform-es2015-sticky-regex",
  "transform-es2015-template-literals",
  "transform-es2015-typeof-symbol",
  "transform-es2015-unicode-regex",
  "transform-es3-member-expression-literals",
  "transform-es3-property-literals",
  "transform-es5-property-mutators",
  "transform-eval",
  "transform-exponentiation-operator",
  "transform-export-extensions",
  "transform-flow-comments",
  "transform-flow-strip-types",
  "transform-function-bind",
  "transform-jscript",
  "transform-object-assign",
  "transform-object-rest-spread",
  "transform-object-set-prototype-of-to-assign",
  "transform-proto-to-assign",
  "transform-react-constant-elements",
  "transform-react-display-name",
  "transform-react-inline-elements",
  "transform-react-jsx",
  "transform-react-jsx-compat",
  "transform-react-jsx-self",
  "transform-react-jsx-source",
  "transform-regenerator",
  "transform-runtime",
  "transform-strict-mode",
  "undeclared-variables-check",
];

export const PRESETS = {
  "es2015": [
    "check-es2015-constants",
    "transform-es2015-arrow-functions",
    "transform-es2015-block-scoped-functions",
    "transform-es2015-block-scoping",
    "transform-es2015-classes",
    "transform-es2015-computed-properties",
    "transform-es2015-destructuring",
    "transform-es2015-duplicate-keys",
    "transform-es2015-for-of",
    "transform-es2015-function-name",
    "transform-es2015-literals",
		// 'transform-es2015-modules-amd',
    "transform-es2015-modules-commonjs",
		// 'transform-es2015-modules-systemjs',
		// 'transform-es2015-modules-umd',
    "transform-es2015-object-super",
    "transform-es2015-parameters",
    "transform-es2015-shorthand-properties",
    "transform-es2015-spread",
    "transform-es2015-sticky-regex",
    "transform-es2015-template-literals",
    "transform-es2015-typeof-symbol",
    "transform-es2015-unicode-regex",
    "transform-regenerator",
  ],
  "es2016": [
  ],
  "es2017": [
  ],
  "latest": [
  ],
  "react": [
  ],
  "stage-0": [
  ],
  "stage-1": [
  ],
  "stage-2": [
  ],
  "stage-3": [
  ],
	// 'es2015-no-common-js',
	// 'es2015-loose',
};

export const CONTAINING_PRESETS = {
  "stage-0": ["stage-1", "stage-2", "stage-3"],
  "stage-1": ["stage-2", "stage-3"],
  "stage-2": ["stage-3"],
  "latest": ["es2015", "es2016", "es2017"],
};

export const PRESET_NAMES = Object.keys(PRESETS);
